# Use the official Node.js image as the base image
FROM node:21-bullseye

# Set the working directory inside the container
WORKDIR /Fabros_Robert_ui_garden_build_checks

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json .

# Install the application dependencies
RUN npm ci

RUN npx playwright install --with-deps chromium

COPY . .

# Define the command to run the Storybook server
CMD ["npm", "run", "ci:test"]
